name: eraasoft_ecommerce
description: A new Flutter application.


publish_to: 'Eraasoft'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #ui_enhancment
  buildcondition: ^0.0.4
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  #bloc
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  get: ^4.6.1
  #service
  dio: ^4.0.4
  shared_preferences: ^2.0.11
  hive: ^2.0.5
  #utils
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0











dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/gifs/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
